name: pre-merge-workflow
on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: A job to run all the golang unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unit Tests
        id: unit-test
        uses: ./
        with:
          test-type: "unit-test"
